apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: semantic-bus-org
  namespace: default
spec:
  secretName: semantic-bus-org-tls
  issuerRef:
    name: letsencrypt-staging
  commonName: prod.semantic-bus.org
  dnsNames:
  - prod.semantic-bus.org
  acme:
    config:
    - http01:
       ingressClass: nginx
      domains:
      - semantic-bus.org
    - http01:
        ingress: test-ingress
      domains:
      - prod.semantic-bus.org