apiVersion: v1
kind: Service
metadata:
  name: frontend-service-direct
  namespace: kube-system
  labels:
    app: semanticbus
    tier: frontend
spec:
  type: LoadBalancer
  loadBalancerIP: 146.148.8.97
  ports:
    # the port that this service should serve on
  - port: 80
  selector:
    app: semanticbus
    tier: frontend
---

apiVersion: v1
kind: ReplicationController
metadata:
  name: frontend
  namespace: kube-system
  # these labels can be applied automatically
  # from the labels in the pod template if not set
  labels:
    app: semanticbus
    tier: frontend
spec:
  # this replicas value is default
  # modify it according to your case
  replicas: 1
  # selector can be applied automatically
  # from the labels in the pod template if not set
  # selector:
  #   app: guestbook
  #   tier: frontend
  template:
    metadata:
      labels:
        app: semanticbus
        tier: frontend
    spec:
      containers:
      - name: semanticbus-front
        image: semanticbus/semanticbus
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 3000m
            memory: 3000Mi
        env:
        - name: GET_HOSTS_FROM
          value: env
          # value: dns
          # If your cluster config does not include a dns service, then to
          # instead access environment variables to find service host
          # info, comment out the 'value: dns' line above, and uncomment the
          # line below.
          # value: env
        - name: PORT
          value: "80"
        - name: AMQPHOST
          value: "dataPlayersProd"
        - name : CONFIG_URL
          value : "http://app-cee3fd62-a81e-48b2-a766-a8be305d5fa9.cleverapps.io/file/prod"
        ports:
        - containerPort: 80
