apiVersion: v1
kind: ReplicationController
metadata:
  name: rabbit
  namespace: kube-system
  # these labels can be applied automatically
  # from the labels in the pod template if not set
  labels:
    app: semanticbus
    tier: amqp
spec:
  # this replicas value is default
  # modify it according to your case
  replicas: 1
  # selector can be applied automatically
  # from the labels in the pod template if not set
  # selector:
  #   app: guestbook
  #   tier: frontend
  template:
    metadata:
      labels:
        app: semanticbus
        tier: amqp
    spec:
      containers:
      - name: semanticbus-amqp
        image: semanticbus/rabbitmq-stomp
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 2000m
            memory: 3000Mi
        env:
        - name: version
          value: prod/1.0
        - name: RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS
          value: -rabbit levels [{file,[{file,"/var/log/rabbitmq/error.log"},{level,debug},{date,"$D0"},{size,10485760},{count,3}]},{console,[{enabled,true}]}]
          # value: dns
          # If your cluster config does not include a dns service, then to
          # instead access environment variables to find service host
          # info, comment out the 'value: dns' line above, and uncomment the
          # line below.
          # value: env
        ports:
        - containerPort: 15672
        - containerPort: 61613
        - containerPort: 15674
