apiVersion: v1
kind: Service
metadata:
  name: rabbit-service-direct-simple
  namespace: kube-system
  labels:
    app: semanticbus
    tier: amqp-simple
spec:
  type: LoadBalancer
  loadBalancerIP: 35.195.196.184
  ports:
    # the port that this service should serve on
  - port: 15672
    name : management
  - port: 15674
    name : stomp
  - port: 5672
    name : amqp
  selector:
    app: semanticbus
    tier: amqp-simple
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: rabbit-simple
  namespace: kube-system
  # these labels can be applied automatically
  # from the labels in the pod template if not set
  labels:
    app: semanticbus
    tier: amqp-simple
spec:
  # this replicas value is default
  # modify it according to your case
  replicas: 1
  # selector can be applied automatically
  # from the labels in the pod template if not set
  # selector:
  #   app: guestbook
  #   tier: frontend
  template:
    metadata:
      labels:
        app: semanticbus
        tier: amqp-simple
    spec:
      containers:
      - name: semanticbus-amqp-simple
        image: semanticbus/rabbitmq-stomp
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 2000m
            memory: 3000Mi
        env:
        - name: version
          value: prod/1.0
          # value: dns
          # If your cluster config does not include a dns service, then to
          # instead access environment variables to find service host
          # info, comment out the 'value: dns' line above, and uncomment the
          # line below.
          # value: env
        ports:
        - containerPort: 15672
        - containerPort: 61613
        - containerPort: 15674
        - containerPort: 5672
        
