apiVersion: v1
kind: ReplicationController
metadata:
  name: semanticbus-timer
  namespace: kube-system
  # these labels can be applied automatically
  # from the labels in the pod template if not set
  labels:
    app: semanticbus
    tier: timer
spec:
  # this replicas value is default
  # modify it according to your case
  replicas: 1
  # selector can be applied automatically
  # from the labels in the pod template if not set
  # selector:
  #   app: guestbook
  #   tier: frontend
  template:
    metadata:
      labels:
        app: semanticbus
        tier: timer
    spec:
      containers:
      - name: semanticbus-timer
        image: semanticbus/semanticbus-timer
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
        env:
        - name: version
          value: prod/0.9.0
          # value: dns
          # If your cluster config does not include a dns service, then to
          # instead access environment variables to find service host
          # info, comment out the 'value: dns' line above, and uncomment the
          # line below.
          # value: env
        - name : CONFIG_URL
          value : "http://data-players.com/config/prdTest.json"
        ports:
        - containerPort: 80
