apiVersion: v1
kind: Service
metadata:
  name: semanticbus-traefik-service
spec:
  selector:
    app: semanticbus
    tier: frontend
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: semanticbus-traefik-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: semantic-bus.org
    http:
      paths:
      - backend:
          serviceName: semanticbus-traefik-service
          servicePort: 80
