apiVersion: v1
kind: Service
metadata:
  name: semanticbus-traefik-service
  namespace: kube-system
spec:
  selector:
    app: semanticbus
    tier: frontend
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: semanticbus-traefik-ingress
  namespace: kube-system
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host : 35.195.203.5
    http:
      paths:
      - path : /
        backend:
          serviceName: semanticbus-traefik-service
          servicePort: 80
