---
apiVersion: v1
kind: Service
metadata:
  name: mongo2
  namespace: db
  labels:
    name: mongo2
    environment: prod
spec:
  ports:
  - port: 27017
    targetPort: 27017
  clusterIP: None
  selector:
    role: mongo2
    environment: prod
---
apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: mongo2
  namespace: db
  labels:
    role: mongo
    environment: prod
spec:
  serviceName: "mongo2"
  replicas: 2
  selector:
    matchLabels:
      role: mongo2
      environment: prod
  template:
    metadata:
      labels:
        role: mongo2
        environment: prod
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mongod2
          image: mongo:3.6
          resources:
            requests:
              cpu: 500m
              memory: 500Mi
          command:
            - mongod
            - "--replSet"
            - rs0
            - "--bind_ip_all"
            - "--repair"
            - "--noprealloc"
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-storage3
              mountPath: /data/db2
        - name: mongo-sidecar
          image: cvallance/mongo-k8s-sidecar
          env:
            - name: MONGO_SIDECAR_POD_LABELS
              value: "role=mongo,environment=prod"
            - name: KUBE_NAMESPACE
              value: "db"
      volumes:
        - name: mongo-storage3
          persistentVolumeClaim:
            claimName: mongo-claim2

