kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongo-claim
  namespace: db
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
  storageClassName: ssd
